### ISSUE TITLE
Link to documentation?

### ISSUE THREAD

**Issue by judgej** [AuthorizeNet/accept-sample-app#1]
Looks very exciting. It would be worth putting a link in the readme to the product page or documentation pages on authorize.net.

**Comment by brianmc** [comment]
Updated the readme with documentation link for our Accept Customer API.  Accept.js documentation is coming soon and will be available for the General Availability launch.

**Comment by thetwosents** [comment]
Hey @brianmc Ive been actively waiting to see some documentation come out for the accept js solution and haven't seen or heard anything. Any updates since June?

**Comment by brianmc** [comment]
Hi @thetwosents I can see now the link is quite subtle in the Accept.js section, sorry about that.  Here's the actual URL:  http://developer.authorize.net/api/reference/features/acceptjs.html

**Comment by judgej** [comment]
Nice. So it just plugs onto the front end/web client, and you can continue to use all the same back end APIs (though possibly with slightly different validation, since the merchant application no longer deals with all the credit card details). That will make migration of existing sites pretty straight-forward.
