### ISSUE TITLE
Adding a New Payment always says "Address and Zip are required"

### ISSUE THREAD

**Issue by Gromph** [AuthorizeNet/accept-sample-app#10]
I got the sample up and running by doing the following:
I created a sandbox account on authorize.net and set the API_LOGIN_ID and TRANSACTION_KEY in the environment. Then I added a profile using the Customer Information Manage on sandbox.authorize.net. 
I'm running on Windows 10, php 5.6. I'm running using the php built in webserver: php -S localhost:8000
(It would have been nice to have more explicit step by step instructions for setting up an account, test profile, and running php)

When I click the Payment tab, fill out the info with a test card then click Save. I always get the error: "Address and Zip are required"

I've tried adding a shipping address which works, but then going back and adding a payment method results in the same error.

Going to Profile Tab and then Add a New Payment Method also always results in the same error

**Comment by Gromph** [comment]
I've tried a few more things that have not worked:
1. in sandbox account went to Account -> Payment Form -> Form Fields and unchecked everything

2. in sandbox account went to Account -> Address Verification Service  and unchecked Enable Filter, as well as set everything to Allow

**Comment by adavidw** [comment]
I see this myself, not only on adding a payment method, but editing existing as well.

**Comment by brianmc** [comment]
Sorry I had configured it to not show Billing address to demo that and forgotten to switch it back.  See commit  https://github.com/AuthorizeNet/accept-sample-app/commit/54f13dad464448485d2f6e79053e4354f048aa15 

should work now.
