### ISSUE TITLE
Session Start Error in index.php

### ISSUE THREAD

**Issue by FritzTGreen** [AuthorizeNet/accept-sample-app#11]
index.php attempts to start the PHP session on line 5 _after_ headers and three lines of output, which throws a PHP Warning:  session_start() [<a href='function.session-start'>function.session-start</a>]: Cannot send session cache limiter - headers already sent (output started at /home/public_html/accept/index.php:4) in /home/public_html/accept/index.php on line 5

**Comment by adavidw** [comment]
Fixed in PR #14

**Comment by brianmc** [comment]
Fixed.  Thanks for reporting.
