### ISSUE TITLE
OTS Token access violation 

### ISSUE THREAD

**Issue by carywreams** [AuthorizeNet/accept-sample-app#13]
Receiving this error as a final message:
```
{"messages":{"resultCode":"Error","message":{"code":"E00116","text":"OTS Token access violation"}},"transactionResponse":{}}
```

Any thoughts on how I might fix my setup are appreciated.

### Researched Clues to solve this problem
* Verified api login id and transaction key match sandbox account
* Verified signature key generated for sandbox account (though have not found a place to provide this to the sample app)

### Setup
* Sample App installed on a VM running ubuntu1204 server with php_curl enabled 
* self-signed SSL cert on VM, browser ignoring security setting warning
* apache redirect directive sends all http requests to https on the VM
* api login id and transacton id placed in httpd.conf using setenv directive
* PHP 5.3, Apache 2.2.22
* created a single Customer ID at the sandbox
* the Customer Profile ID from the sandbox passes sample app login

### Other
* sample app correctly pulls credit card number for customer profile (4111111111111111) when presenting payment screen;
* have successfully used the sample app to change credit card expiry details; changes appear at sandbox web site, so connectivity looks good;

### DevTools Screen Grab
![x](https://cloud.githubusercontent.com/assets/409739/22113732/e729f27c-de2c-11e6-9212-4a5172b81672.png)

Thanks,
Cary

**Comment by brianmc** [comment]
Hi Cary,

We have had some issues with our tokenization backend in sandbox this evening.  They should be resolved now.

Brian

**Comment by carywreams** [comment]
Thanks. Will schedule some time this morning to re-try and update or close this issue.

**Comment by carywreams** [comment]
No change in behavior on this side; receiving the same OTS Token Access Violation.

Is there anything to correct or change related to the message at the top of the console?
```
XMLHttpRequest cannot load https://jstest.authorize.net/v1/AcceptCore.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://192.168.122.234' is therefore not allowed access.
```

The origin location is the VM running the sample app.

**Comment by carywreams** [comment]
FWIW, many of the attempted transactions are appearing in my sandbox CIM customer profile as 'voided.'

### History for Sandbox Customer ID
![void](https://cloud.githubusercontent.com/assets/409739/22152539/0ba088ac-dee9-11e6-9568-2e1f7fb0b54c.png)

### Sample Transaction Detail from Sandbox
![detail](https://cloud.githubusercontent.com/assets/409739/22152552/18b8ad30-dee9-11e6-9fb3-101b797c1cc3.png)

**Comment by carywreams** [comment]
Noticed the values on the transactions seem to arriving as "0.00" rather than any amount entered in the form. Could this contribute?
![zeroes](https://cloud.githubusercontent.com/assets/409739/22257455/bc740a2c-e223-11e6-8a51-b1996bdd425a.png)

**Comment by carywreams** [comment]
* have confirmed sandbox is __not__ in _Test Mode._

**Comment by rhldr** [comment]
The voided transactions shown above are expected if you create a customer profile and have validation mode set to live mode.  When the customer profile is created, the gateway performed a zero dollar authorization to confirm the card is accepted. In your example, you describe creating a customer profile, modifying the customer profile which both working correctly.  

And then it appears you're attempting a second transaction using Accept.js using a card number and it's returning the error when you submit using Accept.js.   Is this correct?

**Comment by carywreams** [comment]
Thanks @rhldr,

### Answers
* Customer information was initially entered through CIM at the Sandbox; not thru the sample app
* The Customer ID was used on the login screen prior to the "Pay" button appearing

### Sequence
* login, using Customer App
* click "Pay" buttong
* enter requested information
* receive Transaction Unsuccessful 

__Follow Up__
I confirmed the sandbox "Test Mode" setting was set to "Live." But, can you tell me more about "validation mode?" Perhaps there's something to that.

**Comment by brianmc** [comment]
This error results from the public client key used to get the Accept Payment Nonce, not matching the merchant credentials used to create a transaction with the Payment Nonce.  Can you make sure these two keys are in sync for your sandbox merchant?  In the sample App the Accept.js client key is set at https://github.com/AuthorizeNet/accept-sample-app/blob/master/acceptJSCaller.js LINE 89

Hope this helps

**Comment by carywreams** [comment]
will schedule time this morning to verify this. Thank you.

**Comment by carywreams** [comment]
# RESOLVED
I also changed the apiLoginId on line 90 to match my sandbox. With both changes, the transaction returned a success.

__Thank you very much.__


## Final Question
What do you think about updating the README to include these two steps in the "How to Use the Sample App" section, either before or after the note on updating httpd.conf with environment variables for the api login id and the transaction key ?

I can submit a pull request for the change or just leave this issue open for one of the team to do it.

Your call. Let me know.

**Comment by brianmc** [comment]
Thanks @carywreams !
