### ISSUE TITLE
AcceptCore.js not available.

### ISSUE THREAD

**Issue by rob-gordon** [AuthorizeNet/accept-sample-app#19]
I'm not able to run this sample app because jstest.authorize.net isn't serving `AcceptCore.js`. This is requested directly in this Sample App, but it's also requested within the sandbox script (which is being served, strangely) that's suggested on [this page](https://developer.authorize.net/api/reference/features/acceptjs.html).

    XMLHttpRequest cannot load https://jstest.authorize.net/v1/AcceptCore.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://authorize.dev' is therefore not allowed access.

**Comment by brianmc** [comment]
Sorry @rob-gordon that's a spurious error, we have fixed it in an upcoming release.  But it does not affect the functionality.  Are you able to run the sample for Accept.js ok apart from this?

Brian

**Comment by rob-gordon** [comment]
No, not successfully. For one, even though I can log in with a Customer Profile ID, I still _Missing or invalid token_. When I try to charge a credit card using Pay with Accept.js I get the following output:

`{"messages":{"resultCode":"Error","message":{"code":"E00116","text":"OTS Token access violation"}},"transactionResponse":{}}`

![screen shot 2017-02-19 at 6 59 50 pm](https://cloud.githubusercontent.com/assets/159949/23104868/18918688-f6d6-11e6-8481-d93da741580c.png)

**Comment by rob-gordon** [comment]
I'm still struggling with this unfortunately
