### ISSUE TITLE
Pre fill in billing name and address?

### ISSUE THREAD

**Issue by markengelhardt** [AuthorizeNet/accept-sample-app#2]
If I already know the customers billing address info, how can I pass it along to the Payment form so the end user does not have to fill it in?

**Comment by brianmc** [comment]
We don't have pre-fill right now although it's definitely coming in a future release.  In the meantime, you can specify to not show the billing address at all and then update the new profile with the known address (via API)

**Comment by markengelhardt** [comment]
That sounds like it will work for my situation, but I can't find the trick to keep from showing the billing address fields. Can you share it?

**Comment by markengelhardt** [comment]
OK, I found it... I added a line to the   hostedProfileSettings XML 
`
<setting><settingName>hostedProfileBillingAddressOptions</settingName><settingValue>showNone</settingValue></setting>
`

**Comment by markengelhardt** [comment]
So when I hide the billing address, I get this error when I attempt to submit a credit card:

"Error","messageCode":"E00027","messageText":"Address and Zip are required."

Any suggestions?

**Comment by brianmc** [comment]
Looks like you may have those set in your payment form settings.  Do you use SIM/payment form?

**Comment by markengelhardt** [comment]
I am using the form hosted by authorizenet --  https://test.authorize.net/customer/addPayment
