### ISSUE TITLE
Possible to add other fields to Accept.dispatchData()?

### ISSUE THREAD

**Issue by rob-gordon** [AuthorizeNet/accept-sample-app#22]
I would like to set things like the user's name and the invoice number. Is it possible to do this with the `secureData` that is passed to Accept.dispatchData?

    var secureData = {},
    authData = {},
    cardData = {};

    cardData.cardNumber = document.getElementById('CARDNUMBER_ID').value;
    cardData.month = document.getElementById('EXPIRY_MONTH_ID').value;
    cardData.year = document.getElementById('EXPIRY_YEAR_ID').value;
    cardData.zip  = document.getElementById('ZIP_CODE').value;
    cardData.cardCode  = document.getElementById('CARD_CODE').value;
       
    authData.clientKey = 'xxx';
    authData.apiLoginID = 'xxx';

    secureData.cardData = cardData;
    secureData.authData = authData;

    /* Something like this? */
    secureData.userFields = {
      jobNumber: document.getElementById('JOB_NUMBER').value
    };

    /* Or this? */
    secureData.jobNumber = document.getElementById('JOB_NUMBER').value

**Comment by rob-gordon** [comment]
Posted the same question to StackOverflow: http://stackoverflow.com/questions/42530120/authorize-net-accept-js-integration-attaching-an-invoice-number

**Comment by brianmc** [comment]
Hi Rob,

Those details would be passed when you make the createTransaction request rather than when you dispatch the secure data.  In other words we don't need that info to create a secure element for the Card data.

Brian
