### ISSUE TITLE
Sample not running

### ISSUE THREAD

**Issue by patriotga2** [AuthorizeNet/accept-sample-app#23]
I am trying to implement authorize.net into a website I am building.  It has not been pleasant. I initially was using the AIM/SIM and it gave me an error saying it could not find a certain file that was not included anywhere in the github download. This issue was previously brought up in the forum but did not have any corrective answers provided. When I did an online chat the rep could offer no help but directed to the JScaller and accept Hosted stating that this was your new implementation. I uploaded your sample so that I could make heads or tails of what i needed to extract from the code and what belonged to the multiple other stuff and after removing all the login stuff from the code seeings that no matter what was used for the login id it said login invalid, the sample does not run. I put my card number in and the only thing that happens is the button opaques and says processing and doesn't go anywhere. The people I am developing the website for are now becoming irate because it has been a number of days since I told them all I needed to do was implement the payment gateway, and here we are. Hands tied. Some useable integration guidelines would be great. Thanks.

**Comment by patriotga2** [comment]
Also. on the form when I made the order info show true the pay button disappeared, so I deduced that it was probably the height of the form that was making it cut off and so I changed the height to 800px and viola, problem solved, except that it then dawned on me that what happens when the screen comes in (mobile) and just as suspected when I pulled it up on my phone the bottom of the form was cut off. Not that this is something that I now would just have to  use media css for various screen widths, but  your documentation says mobile optimized.

**Comment by brianmc** [comment]
Have you checked out our Step-by-step guide (linked off the main readme)? https://github.com/AuthorizeNet/accept-sample-app/blob/master/README-AcceptHosted.md

If there are any steps missing or unclear there please let us know and thanks again for the feedback.
