### ISSUE TITLE
The Customer ID in the config file

### ISSUE THREAD

**Issue by merlin500** [AuthorizeNet/accept-sample-app#26]
does not work for the login page.  Am i missing something?

**Comment by brianmc** [comment]
You need to plug in your own sandbox credentials and then have a valid customer profile ID.  You can create own for your sandbox account here: https://developer.authorize.net/api/reference/index.html#customer-profiles-create-customer-profile

We understand this can be a barrier to getting the sample app up and running so we'll probably remove this constraint from the "Pay" examples soon.

**Comment by instantwpuserwin** [comment]
I get this error. I did create user profile.

But I have not setup  environment variables for API_LOGIN_ID and TRANSACTION_KEY. 
I have a shared windows hosting account and hence not sure if I can setup env variables via FastCGI Settings -> Environment Variables..  

Is there any alternative to env variables setup?
