### ISSUE TITLE
Troubles with ApplePay integration 

### ISSUE THREAD

**Issue by MishaGri** [AuthorizeNet/accept-sample-app#31]
Transaction fails with error code 153.
Here var_dump SimpleXMLElement object with payment request:

object(SimpleXMLElement)#659 (2) {
  ["merchantAuthentication"]=>
  object(SimpleXMLElement)#345 (2) {
    ["name"]=>
    string(9) "3x27URbWp"
    ["transactionKey"]=>
    string(16) "672HMz5WP6czF26K"
  }
  ["transactionRequest"]=>
  object(SimpleXMLElement)#698 (4) {
    ["transactionType"]=>
    string(22) "authCaptureTransaction"
    ["amount"]=>
    string(4) "1.00"
    ["currencyCode"]=>
    string(3) "USD"
    ["payment"]=>
    object(SimpleXMLElement)#339 (1) {
      ["opaqueData"]=>
      object(SimpleXMLElement)#692 (2) {
        ["dataDescriptor"]=>
        string(26) "COMMON.APPLE.INAPP.PAYMENT"
        ["dataValue"]=>
        string(4946) "eyJkYXRhIjoieUR1....oiRUNfdjEifQ"
      }
    }
  }
}
 
And json encoded response
 
"{"messages":{"resultCode":"Error","message":{"code":"E00027","text":"The transaction was unsuccessful."}},"transactionResponse":{"responseCode":"3","authCode":{},"avsResultCode":"P","cvvResultCode":{},"cavvResultCode":{},"transId":"0","refTransID":{},"transHash":"8FE725322ECC38B5D6B566144CCCF45A","testRequest":"0","accountNumber":{},"accountType":{},"errors":{"error":{"errorCode":"153","errorText":"There was an error processing the payment data. Unable to decrypt data."}},"transHashSha2":{}}}"
 

Why transaction may fail?

**Comment by gnongsie** [comment]
Hi,

We're trying to resolve this issue. But it seems that there can be a number of reasons that an error like this can be returned.

While acknowledging that it has been a long time since this issue was raised, and apologizing for the late response, I'd like to ask if this issue still persists.

**Comment by MishaGri** [comment]
Hi, I don’t remember how I solved this problem, but the error was in the request. Now this error is not reproduced.

**Comment by gnongsie** [comment]
Hi @MishaGri ,

Thank you for verifying this. I'll be closing this issue for now. Please let us know if you face any other issues.

**Comment by neowinston** [comment]
I'm having the same issue now. I get a valid response from Apple but there is something wrong with my POST request to Authorize.Net. I'm guessing also that the problem could be with the opaqueData field, which comes from Apple Pay side, because when I use a credit card number instead, it works just fine. Any ideas on how to solve this problem? Thank you!
