### ISSUE TITLE
Security vulnerability in Accept.js documentation

### ISSUE THREAD

**Issue by fulldecent** [AuthorizeNet/accept-sample-app#34]
Accept.js documentation is here: https://developer.authorize.net/api/reference/features/acceptjs.html#Usage_With_Your_Own_Payment_Form

Under the section: INTERCEPTING THE FORM SUBMISSION you present an example that explains how to implement sending credit card details to Authorize.net so that they are not sent to the merchant server. This claims to achieve PCI compliance.

```html
<form id="paymentForm"
    method="POST"
    action="https://YourServer/PathToExistingPaymentProcessingScript">
    <input type="text" name="cardNumber" id="cardNumber" placeholder="cardNumber"/> <br><br>
    <input type="text" name="expMonth" id="expMonth" placeholder="expMonth"/> <br><br>
    <input type="text" name="expYear" id="expYear" placeholder="expYear"/> <br><br>
    <input type="text" name="cardCode" id="cardCode" placeholder="cardCode"/> <br><br>
    <input type="hidden" name="dataValue" id="dataValue" />
    <input type="hidden" name="dataDescriptor" id="dataDescriptor" />
    <button>Pay</button>
</form>
```

Consider the HTML5 standard behavior for buttons https://www.w3.org/TR/2017/REC-html51-20171003/sec-forms.html#element-attrdef-button-type the default behavior for buttons is to submit the form.

The Authorize.net implementation guide only states:

> For our sample HTML payment form above, we would replace line number 10 with the following. The sendPaymentDataToAnet() method will be defined in the next section.

This is insufficient. You should also specify that the attribute `type="button"` MUST be added.

As current, an implementation which follows your instructions as above will violate PCI since it *may* send payment details to the merchant. Also, this may be difficult to diagnose because you will only notice with clients that have javascript turned off.

**Comment by Fabian05galvis** [comment]
After doing that, he returns an encrypted information to me, what to do with it?

**Comment by kreitje** [comment]
Not to mention they have the name fields set on the inputs.  The javascript then uses `document.getElementById` to get the values.

**Comment by gnongsie** [comment]
This has been addressed. Kindly review the modified example on the site. I'll be closing this based on that change. Feel free to re-open if there are any further issues.

**Comment by fulldecent** [comment]
The code in question on the website has not been updated and it is still a security vulnerability.
