### ISSUE TITLE
Email to User After Payment (AcceptHosted)

### ISSUE THREAD

**Issue by MtarantoOa** [AuthorizeNet/accept-sample-app#39]
Hi Guys,

Im using the AcceptHosted solution on our application.

The question that I have is after the payment has successful processed and I get the response, the user should not receive an email form authorize with the invoice or receipt for the payment?

That is something I will need to configure? Or I have to doit my self?

Dose authorize have that service?

Thanks for your help!

**Comment by gnongsie** [comment]
Hi @MtarantoOa ,

I have a question regarding who you mean by "user"?

If you are saying that you (as a merchant) do not want to receive any email about the invoice or the receipt, you can disable this feature by following [this link](https://support.authorize.net/s/article/How-can-I-disable-merchant-email-receipts).

Regards,
Gabriel

**Comment by chsriniv9** [comment]
Based on the steps provided by @gnongsie above, closing this issue. Please feel free to re-open if further support needed on this topic.
