### ISSUE TITLE
Payment Gateway Errors: "Missing or invalid token" and  "Cannot read properties of null (reading 'billTo')"

### ISSUE THREAD

**Issue by AkshajPillaiAstonous** [AuthorizeNet/accept-sample-app#59]
I'm encountering issues integrating a Salesforce Apex controller with a Lightning Web Component to process payments using Authorize.Net.

Errors:

    "Missing or invalid token": When I click "Create Token," I receive this error, preventing me from redirecting to the Authorize.Net payment page.

    "Cannot read properties of null (reading 'billTo')": This error occurs in the LWC's JavaScript (main.bundle.js). It suggests an issue with how the billing address data is being sent to Authorize.Net.

Environment:

    Salesforce Org Type: [Sandbox]

Steps to Reproduce:

    Set up Authorize.Net Sandbox:
        Create a sandbox account on https://developer.authorize.net/
        Create a customer profile in the Customer Information Manager.
    Deploy Code:
        Deploy the Apex class and LWC to your Salesforce org.
    Access the LWC:
        Go to the component's URL within the Salesforce UI.
    Trigger the Error:
        Click the "Create Token" button.

Observations:

    I've verified my API_LOGIN_ID and TRANSACTION_KEY in the Apex controller.

Request:

    Troubleshooting Guidance: Please help identify the root cause of the "Missing or invalid token" and "Cannot read properties of null" errors and provide solutions.
    Best Practices: Are there any best practices or optimizations for this type of integration?

**Comment by AkshajPillaiAstonous** [comment]
<img width="1440" alt="image" src="https://github.com/AuthorizeNet/accept-sample-app/assets/165137381/32faccb0-679b-4822-9d3b-9310cc2704d3">

**Comment by AkshajPillaiAstonous** [comment]
Just needed to remove customerProfileId from request body

**Comment by thepropm** [comment]
Hey @AkshajPillaiAstonous 

from which file we need to remove customerProfileId from request body?
