### ISSUE TITLE
Accept.js in Ionic (javascript) mobile app

### ISSUE THREAD

**Issue by mateosss** [AuthorizeNet/accept-sample-app#8]
Sorry if this is not the right place to open an issue. I didn't find the accept.js repo (don't even know if it exists)

We are using Ionic framework which lets you write multi platform apps using html/css/js. I would like to include accept.js in this types of applications, the problem though, is that accept.js requires a https connection in which the form is being passed to the customer, however the form will be already in the client's device, the application itself will contain it. So when trying to use accept.js it throws the expected error:

```
E_WC_02: A HTTPS connection is required.
```

Would it be possible for accept.js to let non-https served pages make payments, after all, if I didn't misunderstood, the real encryption is needed when contacting authorize.net servers, which I suppose accept.js is already ensuring.

Thanks in advance.

**Comment by brianmc** [comment]
Unfortunately not @mateosss.  Accept.js is sending the credit card information to Authorize.Net so it should never be done over an non-secure channel, that's why this check is in.  Is there no way to make your form page https in ionic, regardless of the http client?

**Comment by mateosss** [comment]
Nope. We ended up using another payment method.
