### ISSUE TITLE
Hosted Pay always says Missing or invalid token.

### ISSUE THREAD

**Issue by Gromph** [AuthorizeNet/accept-sample-app#9]
I'm just starting to play with the sample and trying to get it to work. When I click Hosted Pay I get a Make Payment box that says: Missing or invalid token.
I created a sandbox account on authorize.net and set the API_LOGIN_ID and TRANSACTION_KEY in the environment. Then I added a profile using the Customer Information Manage on sandbox.authorize.net. 
I'm running on Windows 10, php 5.6. I'm running using the php built in webserver: php -S localhost:8000
(It would have been nice to have more explicit step by step instructions for setting up an account, test profile, and running php)

I'm getting this error from php:
/getHostedPaymentForm.php - Call to undefined function curPageURL() in accept-sample-app-master\getHostedPaymentForm.php on line 112

I fixed that error, but still get the same result.

The Pay button doesn't work, but I think it's because it requires to be https 

The Profile, Payment and Shipping Tabs do bring up info from my test customer. So the API_LOGIN_ID and TRANSACTION_KEY appear to be correct.

But trying to add a new payment method always says "Address and Zip are required"   I will add a seperate issue for this.

**Comment by superherogeek** [comment]
I'm having the same issue. "Missing or invalid token" error message on Hosted Pay.  I'm on https, and all the customer information appears (that I, too, had to enter manually in the Customer Information Manager sandbox).  Any suggestions from the devs?

**Comment by JoeHEZHAO** [comment]
Also have the same problem; Having tried many many ways but no result. Can any one solve this problem ?

**Comment by brianmc** [comment]
Have you created a Signature Key for your sandbox account?  Sorry I'll update the readme, should be in the guide but not exactly obvious.  We'll also update the readme with better steps to get the sample running.

On the address and zip, that my fault, I tweaked the code to demonstrate something  to a developer.  Will fix that right now.

Brian

**Comment by JoeHEZHAO** [comment]
I have the Signature Key now. Could you please be more specific ?

Looking forward to your updating !

**Comment by brianmc** [comment]
You don't need to do anything with the key on your end, it just needs to be associated with your account in the merchant interface.  Did you try again?  Are you still getting the same error?

**Comment by JoeHEZHAO** [comment]
The same Error "missing or invalid token"

What I did until now is : 
1. set up env log_in_ID and TransactionKey in http.config;
2. open SSL on Mac apache server (https://localhost/  working);
3. In getHostedPaymentForm.php:
          a. change "cancelUrl => curPageURL()" to "cancelUrl => thisPageURL()"
          b. <customer>
                     <id>180894XXXX</id>   // use my own testing account customer ID
                     <email>XXXX@gmail.com</email> // use my own email
              </customer>
4. Generate a Signature Key in sandbox terminal, "Account => API Credentials & Keys =>Create New Keys => New Signature Key"

Am I wrong at certain step ?

Thanks
He Zhao

**Comment by brianmc** [comment]
Are you sure your getHostedPaymentForm call is working and actually returning a token?  You can print out the response and request there to see if they look correct.  Set your credentials right in the xml (as a test only) to check if it's an issue with the env variables.

Brian

**Comment by JoeHEZHAO** [comment]
Brian

No, the getHostedPaymentForm.php return null token. I know problems resides in this file but I barely change a thing in it. I simply change **'<customer> <id>'** with my own customer id and I am sure my env variables are right ( actually I type in api_login_id and transaction_key myself instead of doing it by getenv() method ). 

The Error information is E00001.

Should I include Signature Key into getHostedPaymentForm.php ? 

Can you leave me an email so that I can send my version of sample code to you ?

Thanks a lot for helping me solve this

He Zhao

**Comment by brianmc** [comment]
Make a PR with your sample (no credentials) and I'll test it out

**Comment by JoeHEZHAO** [comment]
Hey Brian

I made it running now. It turns out the customer ID does not matter and I change url back to default (before I changed it for trying). Thank a lot.

I have another problem here: Can I allow customers to choose payment profile (different credit cards) when using SIM (HostedPaymentPage) ? Do customers have to type it in every time ? I believe this can be done easily with CIM ( PaymentProfile )

And after transaction success on HostedPaymentPage, can I have a response as JSON or XML ? I want to store the transaction information (id, date, customer email  etc.) in local database;

I am finding official document about GetHostedPaymentFormRequest API since I want to know all those fields I can define and post. I found this one [https://developer.authorize.net/api/reference/features/accept_hosted.html](url). Is there something else ?

**Comment by brianmc** [comment]
Good news Joe.  You can easily charge customer profiles with our Customers API (CIM) http://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-customer-profile but not (currently) in our Accept Hosted Payment Page (or legacy SIM).  This is a feature we will be looking into adding in the Accept Hosted page in the future.

We're updating the Feature page for Accept Hosted right now (should be available next week) but you have the right page.  If you use the iFrameURLCommunicator you can listen for transactSuccess message and then you will get a JSON string with transaction details.  See the sample app for an example of that.

I'm going to close out this issue now but thanks for the feedback.

Brian

**Comment by JoeHEZHAO** [comment]
Brian 
Thanks for everything. You are very helpful.

My final question is : When I use CIM to create-customer-payment-profile (adding credit card), which includes sensitive credit card information, can I do this on authorize.net server ? I don't want to host dangerous data.

Best
He Zhao

**Comment by brianmc** [comment]
There is indeed a hosted option for CIM, we call it Accept Customer and you can see an example of it when you click on Payment in the sample app.  Also more details here http://developer.authorize.net/api/reference/features/customer_profiles.html

**Comment by JoeHEZHAO** [comment]
Hey Brian

You are right, the add-payment-profile is also hosted by authorize.net. And I find Profile page is hosted either, which is great !

Is there any document telling about all hosted service in CIM ?

Also is there any document talking about how to understand iframeCommunicator ( iCommunicator.html )?

Best
He Zhao

**Comment by JoeHEZHAO** [comment]
Hey Brian

I have known that ,for now, I can only get customerPaymentProfileList by sorting the cardExpireDate. **But I need to get all paymentProfileIDs for a certain customer, only using customerID.** 

Have contributors add more searchType such as customer_Id ? 

Or is there another way to do it ?

Thanks 
He Zhao
